# Generated by Django 4.2 on 2023-04-17 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('16d8fea2-ae60-473a-8f33-6b49def0de8a'), help_text='Уникальный id для каждого жанра', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
            ],
        ),
    ]
