# Generated by Django 4.2 on 2023-04-17 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0004_content_ganre_alter_contenttype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('04162a7a-1656-4876-8719-707b66e229df'), help_text='Уникальный id для каждого жанра', primary_key=True, serialize=False),
        ),
    ]
