# Generated by Django 4.2 on 2023-04-17 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0005_alter_contenttype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Уникальный id для каждого жанра', primary_key=True, serialize=False),
        ),
    ]
