# Generated by Django 4.1.4 on 2023-04-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0008_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
