# Generated by Django 4.1.4 on 2023-04-28 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writer', '0010_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Уникальный id для каждого комментария', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный id для каждой оценки', primary_key=True, serialize=False)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writer.content', verbose_name='Произведение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
