# Generated by Django 4.2 on 2023-05-15 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writer', '0015_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='similar_content',
            field=models.ManyToManyField(blank=True, to='writer.content', verbose_name='Похожие произведения'),
        ),
        migrations.CreateModel(
            name='SimilarityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('+', 'Похоже'), ('-', 'Не похоже')], max_length=1)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_votes', to='writer.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
