# Generated by Django 4.2 on 2023-05-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0016_content_similar_content_similarityvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='similar_content',
        ),
    ]
