# Generated by Django 4.2 on 2023-05-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0017_remove_content_similar_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='similar_content',
            field=models.ManyToManyField(blank=True, to='writer.content', verbose_name='Похожие произведения'),
        ),
    ]
